### ISSUE TITLE
Occasionally Odd Rendering Issue

### ISSUE THREAD

**Issue by trevorwhealy** [bitttttten/mechanical-counter#2]
First things first, what a cool library! I have been trying to achieve something so clean and readable that is built on top of existing animation libraries for years. I add this to fun projects and noticed that it sometimes has a rendering bug.

Example A:
<img width="171" alt="Screenshot 2023-05-02 at 9 54 00 AM" src="https://user-images.githubusercontent.com/14946478/235733529-48b05b63-e34b-4cc9-b59f-347effb87003.png">

Example B:
<img width="199" alt="Screenshot 2023-05-02 at 9 54 09 AM" src="https://user-images.githubusercontent.com/14946478/235733577-1787092f-c39d-48ff-a634-cfe056e49384.png">

Example C:
<img width="191" alt="Screenshot 2023-05-02 at 9 54 37 AM" src="https://user-images.githubusercontent.com/14946478/235733618-aee51b33-88ab-4e47-9557-9a5d18c37956.png">

I reduced my usage to the most basic form I could:
```
<div style={{
   fontFamily: `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, ...`,
}}> <MechanicalCounter text={animatedValue} /> </div>
```

It appears that this is primarily caused by the nested span element.

<img width="426" alt="Screenshot 2023-05-02 at 9 55 30 AM" src="https://user-images.githubusercontent.com/14946478/235734309-edcba82e-f24b-4536-aa24-ae993d8f5ef6.png">

You'll notice that the scale value, at rest, is not equal to `1` - though I didn't see any obvious reference to scale in your codebase, I think the culprit must be that the animation is stopping too soon for some reason which leaves the final animation state with some transition values instead of the final values.

**Comment by bitttttten** [comment]
Hey Trevor! Thanks for the kind words.

I see what you mean, maybe I am not being so efficient with my script and there's too much for framer to do because of some kind of layout trashing.. then it explains why the animation gets cut off abruptly.

Were you able to reproduce this across different versions, even different major version of framer motion? 

The scale could be because I am using layoutId and so it animates between visual states in whichever way it can.. i.e. scale.

I am off for a few days so I will not be able to investigate for a while so if you can hold on for a week or so I can investigate!

**Comment by trevorwhealy** [comment]
Your intuition was correct - bumping up the `framer-motion` library to the latest version seems to have solved the issue. Guess that makes sense since the underlying issue seemed to be within their layout engine.

https://user-images.githubusercontent.com/14946478/235805674-552dd52e-6a11-4a98-9824-adb3b8ca214a.mov

Pretty slick. Hope to use this in the future. Thanks!

**Comment by bitttttten** [comment]
Good to hear! I'll go ahead and close up this issue then :)
